"""empty message

Revision ID: 1e11dae9381e
Revises: 6fea886a346e
Create Date: 2026-05-17 16:41:12.044189

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1e11dae9381e'
down_revision: Union[str, Sequence[str], None] = '6fea886a346e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('failed_files', sa.Column('cloudinary_public_id', sa.String(), nullable=True))
    op.add_column('processed_files', sa.Column('cloudinary_public_id', sa.String(), nullable=True))
    op.add_column('processed_files', sa.Column('instagram_media_id', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('processed_files', 'instagram_media_id')
    op.drop_column('processed_files', 'cloudinary_public_id')
    op.drop_column('failed_files', 'cloudinary_public_id')
    # ### end Alembic commands ###
