"""per-user cloudinary credentials

Revision ID: 6dba14c04f3e
Revises: 90e985e9f7ac
Create Date: 2026-05-09 14:58:21.331738

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6dba14c04f3e'
down_revision: Union[str, Sequence[str], None] = '90e985e9f7ac'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('cloudinary_cloud_name', sa.String(), nullable=True))
    op.add_column('users', sa.Column('cloudinary_api_key', sa.String(), nullable=True))
    op.add_column('users', sa.Column('cloudinary_api_secret', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'cloudinary_api_secret')
    op.drop_column('users', 'cloudinary_api_key')
    op.drop_column('users', 'cloudinary_cloud_name')
    # ### end Alembic commands ###
