"""make facebook_name nullable

Revision ID: 6fea886a346e
Revises: 6dba14c04f3e
Create Date: 2026-05-10 16:07:44.594236

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6fea886a346e'
down_revision: Union[str, Sequence[str], None] = '6dba14c04f3e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('waitlist', 'facebook_name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('waitlist', 'facebook_name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
